-- TODO Replace all of this with a template
-- TODO Also right now this just appends each time run
COPY CARE_SITE FROM '/home/vagrant/ohdsi/care_site.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CDM_SOURCE FROM '/home/vagrant/ohdsi/cdm_source.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONCEPT FROM '/home/vagrant/ohdsi/concept.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONCEPT_ANCESTOR FROM '/home/vagrant/ohdsi/concept_ancestor.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONCEPT_CLASS FROM '/home/vagrant/ohdsi/concept_class.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONCEPT_RELATIONSHIP FROM '/home/vagrant/ohdsi/concept_relationship.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONCEPT_SYNONYM FROM '/home/vagrant/ohdsi/concept_synonym.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONDITION_ERA FROM '/home/vagrant/ohdsi/condition_era.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY CONDITION_OCCURRENCE FROM '/home/vagrant/ohdsi/condition_occurrence.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY COST FROM '/home/vagrant/ohdsi/cost.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DEATH FROM '/home/vagrant/ohdsi/death.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DEVICE_EXPOSURE FROM '/home/vagrant/ohdsi/device_exposure.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DOMAIN FROM '/home/vagrant/ohdsi/domain.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DRUG_ERA FROM '/home/vagrant/ohdsi/drug_era.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DRUG_EXPOSURE FROM '/home/vagrant/ohdsi/drug_exposure.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY DRUG_STRENGTH FROM '/home/vagrant/ohdsi/drug_strength.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY LOCATION FROM '/home/vagrant/ohdsi/location.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY MEASUREMENT FROM '/home/vagrant/ohdsi/measurement.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY OBSERVATION FROM '/home/vagrant/ohdsi/observation.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY OBSERVATION_PERIOD FROM '/home/vagrant/ohdsi/observation_period.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY PAYER_PLAN_PERIOD FROM '/home/vagrant/ohdsi/payer_plan_period.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY PERSON FROM '/home/vagrant/ohdsi/person.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY PROCEDURE_OCCURRENCE FROM '/home/vagrant/ohdsi/procedure_occurrence.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY PROVIDER FROM '/home/vagrant/ohdsi/provider.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY RELATIONSHIP FROM '/home/vagrant/ohdsi/relationship.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY VISIT_OCCURRENCE FROM '/home/vagrant/ohdsi/visit_occurrence.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
COPY VOCABULARY FROM '/home/vagrant/ohdsi/vocabulary.csv' DELIMITER E'\t' CSV ENCODING 'UTF8';
